### ISSUE TITLE
Example JS to export vertices is broken

### ISSUE THREAD

**Issue by diclophis** [tangrams/vbo-export#1]
Hello,

I am attempting to use the provided JS to export the vertices from the tangram example map: http://tangrams.github.io/tangram/ However it does not work

Could you possibly post the updated instructions (it appears like the JS structure on the map side has changed, possibly including the use of VAOs which might prevent this approach from working on newer versions of tangram)

Alternatively do you have a hosted map of a version of tangram that this vbo-export project supports?

**Comment by meetar** [comment]
You're right, the JS structure had changed, and I only recently got the export working again… I do plan to update the README as well as link to a hosted version with this functionality built-in, but until then if you'd like a preview of the new solution you can view the work in progress here: https://github.com/meetar/manhattan-project/tree/update

I'll update this issue when the new versions are up.

**Comment by diclophis** [comment]
Ok great, I will continue to follow both projects, and if you feel like there is room for some contribution I wouldn't mind helping out with any bugs / workflow / documentation problems your running into (just open up an issue or something that outlines the problem, and mention me and i will take a stab at it). I have interest in this project for building the 3d data into a minecraft world map, as part of a career/recruitment campaign for my company (we want a 'life size' build of san francisco in game)
